from Buildings.material import LOG, FARMLAND, WATER, AIR, CARROTS, WHEAT, POTATOES

farm = {
    "height": -1,
    "building": [
        [
            [LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, FARMLAND, WATER, FARMLAND, FARMLAND, FARMLAND, FARMLAND, WATER, FARMLAND, LOG],
            [LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, CARROTS, AIR, WHEAT, WHEAT, WHEAT, WHEAT, AIR, POTATOES, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ]
    ]
}
