from Buildings.material import AIR, GRAVEL, GRASS_PATH, DIRT, GREENERY, FENCE, STAIRS_STONE, LOG, FLOWER, TORCH, LEAVES

tree = {
    "height": -1,
    "building": [
        [
            [AIR, AIR, GRAVEL, AIR, GRASS_PATH, GRAVEL, AIR, GRASS_PATH, AIR, AIR],
            [GRASS_PATH, AIR, GRASS_PATH, GRAVEL, GRAVEL, GRASS_PATH, GRAVEL, AIR, GRASS_PATH, GRAVEL],
            [GRASS_PATH, GRAVEL, GRASS_PATH, DIRT, DIRT, DIRT, AIR, GRAVEL, AIR, GRASS_PATH],
            [AIR, GRASS_PATH, GRAVEL, DIRT, GRASS_PATH, DIRT, AIR, GRASS_PATH, AIR, AIR],
            [AIR, AIR, GRAVEL, DIRT, DIRT, DIRT, GRASS_PATH, GRASS_PATH, AIR, GRAVEL],
            [GRASS_PATH, GRAVEL, GRASS_PATH, GRASS_PATH, GRAVEL, GRASS_PATH, GRASS_PATH, GRAVEL, AIR, GRASS_PATH],
            [GRAVEL, GRASS_PATH, GRAVEL, AIR, GRASS_PATH, GRAVEL, GRAVEL, GRASS_PATH, GRAVEL, AIR],
            [AIR, GRASS_PATH, AIR, GRAVEL, GRAVEL, GRASS_PATH, GRAVEL, GRAVEL, AIR, GRASS_PATH],
            [GRASS_PATH, AIR, GRASS_PATH, GRASS_PATH, GRASS_PATH, AIR, GRAVEL, AIR, GRAVEL, GRASS_PATH],
            [GRAVEL, GRASS_PATH, GRAVEL, AIR, AIR, GRAVEL, AIR, GRAVEL, GRASS_PATH, AIR],
        ],
        [
            [AIR, AIR, AIR, GREENERY["FERN"], AIR, AIR, AIR, AIR, FENCE, AIR],
            [AIR, FENCE, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, STAIRS_STONE["E"], STAIRS_STONE["E"], STAIRS_STONE["E"], GREENERY["FERN"], AIR, GREENERY["FERN"],
             AIR],
            [AIR, AIR, AIR, STAIRS_STONE["S"], LOG, STAIRS_STONE["N"], GREENERY["FERN"], AIR, AIR, AIR],
            [AIR, GREENERY["FERN"], AIR, STAIRS_STONE["W"], STAIRS_STONE["W"], STAIRS_STONE["W"], AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, GREENERY["FERN"], AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [GREENERY["FERN"], AIR, AIR, AIR, AIR, AIR, AIR, AIR, FENCE, AIR],
            [AIR, GREENERY["FERN"], AIR, AIR, AIR, GREENERY["FERN"], AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, FLOWER["TULIP"], FENCE, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, LOG, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, TORCH["W"], AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, TORCH["N"], LOG, TORCH["S"], AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, TORCH["E"], AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, LOG, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, LEAVES, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LOG, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, LEAVES, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LOG, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, LEAVES, LEAVES, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, AIR, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LOG, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, LEAVES, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LEAVES, LEAVES, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, LEAVES, LEAVES, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ]
    ]
}
