from Buildings.Materials import AIR, DIRT, BRICKS, LOG, STAIRS_STONE, BED, DOOR, GLASS, TORCH, PLANK, WOOD

mansion = {
    "height": -1,
    "building": [
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, DIRT, AIR],
            [AIR, AIR, DIRT, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             DIRT, AIR],
            [AIR, AIR, DIRT, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             DIRT, AIR],
            [AIR, AIR, DIRT, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             DIRT, AIR],
            [AIR, AIR, DIRT, DIRT, DIRT, DIRT, BRICKS["STONE"], DIRT, DIRT, DIRT, DIRT, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             LOG, AIR],
            [AIR, AIR, BRICKS["STONE"], AIR, AIR, BRICKS["STONE"], BRICKS["STONE"], STAIRS_STONE["N"], AIR, AIR, BRICKS["STONE"],
             AIR],
            [AIR, AIR, BRICKS["STONE"], BED["W_HEAD_TAKEN"], AIR, AIR, AIR, AIR, AIR, AIR, BRICKS["STONE"], AIR],
            [AIR, AIR, BRICKS["STONE"], BED["W_FOOT"], AIR, AIR, AIR, AIR, BED["S_FOOT"], BED["S_HEAD"], BRICKS["STONE"],
             AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], DOOR["S_LOWER"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], GLASS, BRICKS["STONE"], LOG, BRICKS["STONE"], GLASS, BRICKS["STONE"], LOG,
             AIR],
            [AIR, AIR, BRICKS["STONE"], AIR, AIR, BRICKS["STONE"], STAIRS_STONE["N"], AIR, AIR, AIR, BRICKS["STONE"],
             AIR],
            [AIR, AIR, GLASS, AIR, AIR, AIR, AIR, AIR, AIR, AIR, GLASS, AIR],
            [AIR, AIR, BRICKS["STONE"], AIR, AIR, AIR, AIR, AIR, AIR, AIR, BRICKS["STONE"], AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], GLASS, BRICKS["STONE"], DOOR["LEFT_UPPER"], BRICKS["STONE"], GLASS, BRICKS["STONE"],
             LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             LOG, AIR],
            [AIR, AIR, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], STAIRS_STONE["N"], AIR, AIR, AIR, AIR, BRICKS["STONE"],
             AIR],
            [AIR, AIR, BRICKS["STONE"], TORCH["S"], AIR, AIR, AIR, AIR, AIR, TORCH["N"], BRICKS["STONE"], AIR],
            [AIR, AIR, BRICKS["STONE"], AIR, AIR, AIR, AIR, AIR, AIR, AIR, BRICKS["STONE"], AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"], BRICKS["STONE"],
             LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, LOG, AIR],
            [AIR, AIR, LOG, BRICKS["STONE"], STAIRS_STONE["N"], AIR, AIR, AIR, PLANK, PLANK, WOOD["ACACIA"], AIR],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, WOOD["ACACIA"], AIR],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, WOOD["ACACIA"], AIR],
            [AIR, AIR, LOG, WOOD["STRIPPED_OAK"], WOOD["STRIPPED_OAK"], WOOD["STRIPPED_OAK"], LOG, WOOD["STRIPPED_OAK"], WOOD["STRIPPED_OAK"], WOOD["STRIPPED_OAK"],
             LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, LOG, PLANK, PLANK, PLANK, LOG, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, PLANK, BED["N_HEAD"], BED["N_FOOT"], AIR, AIR, AIR, BED["S_FOOT"], BED["S_HEAD"], PLANK, AIR],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, LOG, PLANK, PLANK, PLANK, LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, LOG, PLANK, GLASS, PLANK, LOG, PLANK, GLASS, PLANK, LOG, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, TORCH["E"], AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, GLASS, AIR, AIR, AIR, AIR, AIR, AIR, AIR, GLASS, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, LOG, PLANK, GLASS, PLANK, LOG, PLANK, GLASS, PLANK, LOG, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, LOG, PLANK, PLANK, PLANK, LOG, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, PLANK, TORCH["S"], AIR, AIR, AIR, AIR, AIR, TORCH["N"], PLANK, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, LOG, PLANK, PLANK, PLANK, LOG, PLANK, PLANK, PLANK, LOG, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],

        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, PLANK, AIR, AIR, AIR, AIR, AIR, AIR, AIR, PLANK, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],

        ],
        [
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK, PLANK],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],
            [AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR, AIR],

        ]
    ]
}
